require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SaveMe' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-microphone-stream', :path => '../node_modules/react-native-microphone-stream'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'react-native-geolocation-service', :path => '../node_modules/react-native-geolocation-service'

  target 'SaveMeTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SaveMe-tvOS' do
  # Pods for SaveMe-tvOS

  target 'SaveMe-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
